<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
    <xacro:include filename="robot_values.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link = "chassis"/>
        <origin xyz="-${chassis_x / 2} 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_x / 2} 0 ${chassis_z / 2}"/>
            <geometry>
                <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${chassis_x / 2} 0 ${chassis_z / 2}"/>
            <geometry>
                <box size="${chassis_x} ${chassis_y} ${chassis_z}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_x}" y="${chassis_y}" z="${chassis_z}">
            <origin xyz="${chassis_x / 2} 0 ${chassis_z / 2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- Back Left Wheel Link -->

    <joint name="wbl" type="continuous">
        <parent link="chassis"/>
        <child link="back_left_wheel"/>
        <origin xyz="0 ${chassis_y / 2} ${chassis_z / 2}" rpy="-${pi / 2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="back_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Back Right Wheel Link -->

    <joint name="wbr" type="continuous">
        <parent link="chassis"/>
        <child link="back_right_wheel"/>
        <origin xyz="0 -${chassis_y / 2} ${chassis_z / 2}" rpy="-${pi / 2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="back_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Front Right Wheel Link -->

    <joint name="wfr" type="continuous">
        <parent link="chassis"/>
        <child link="front_right_wheel"/>
        <origin xyz="${chassis_x} -${chassis_y / 2} ${chassis_z / 2}" rpy="-${pi / 2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Front Left Wheel Link -->

    <joint name="wfl" type="continuous">
        <parent link="chassis"/>
        <child link="front_left_wheel"/>
        <origin xyz="${chassis_x} ${chassis_y / 2} ${chassis_z / 2}" rpy="-${pi / 2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <link name="front_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Camera -->

    <joint name="camera_joint" type="fixed">
        <parent link="chassis"/>
        <child link="camera_link"/>
        <origin xyz="${chassis_x - (camera_width / 2)} 0 ${chassis_z + (camera_height / 2)}" rpy="0 0 0"/>
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${camera_width}" y="${camera_length}" z="${camera_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="chassis"/>
        <child link="imu_link"/>
        <origin xyz="${camera_width / 2} 0 ${chassis_z + (camera_height / 2)}" rpy="0 0 ${pi}"/>
    </joint>

    <link name="imu_link">
        <visual>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_width} ${camera_length} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="${camera_width}" y="${camera_length}" z="${camera_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
</robot>
