<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">
    <xacro:property name="offset" value="39.3701"/>
    <xacro:property name="chassis_x" value="24"/>
    <xacro:property name="chassis_y" value="18"/>
    <xacro:property name="chassis_z" value="8"/>
    <xacro:property name="wheel_radius" value="4"/>
    <xacro:property name="wheel_length" value="4"/>
    <xacro:property name="wheel_separation" value="30"/>
    <xacro:property name="lidar_radius" value="${0.05 * offset}"/>
    <xacro:property name="lidar_height" value="${0.04 * offset}"/>

    <xacro:property name="camera_length" value="${0.09 * offset}"/>
    <xacro:property name="camera_width" value="${0.025 * offset}"/>
    <xacro:property name="camera_height" value="${0.055 * offset}"/>
</robot>