# Map server parameters
map_server:
  # Frame ID for the map
  map_frame: "map"
  
  # Resolution of the map (meters per pixel)
  resolution: 0.05
  
  # Origin of the map (bottom-left corner in meters)
  origin_x: -10.0
  origin_y: -10.0
  
  # Occupied threshold for the map (values above this threshold are considered occupied)
  occupied_thresh: 0.65
  
  # Free threshold for the map (values below this threshold are considered free)
  free_thresh: 0.196
